#!/usr/bin/env ruby

require "pry"
require "pry-byebug"

class Grid
  EMPTY = ".".freeze
  SPLITTER = "^".freeze
  STARTING_POINT = "S".freeze

  attr_accessor :rows, :current_row_index,
                :paths_arriving_at_index

  def initialize(input_string)
    self.current_row_index = 0
    self.rows = input_string.split("\n")

    final_row = rows.last

    [*rows.reject! { |row| row =~ /\A\.+\z/ }, final_row]

    self.paths_arriving_at_index = [0] * rows.first.size

    paths_arriving_at_index[current_row_starting_point] = 1
  end

  def process_beam
    until done_processing?
      build_path_count_log_entry
      self.current_row_index += 1
    end

    paths_arriving_at_index.sum
  end

  def done_processing?
    current_row_index >= rows.size - 1
  end

  def build_path_count_log_entry
    reachable_splitter_indexes_in_next_row = current_row_starting_points.select do |column_index|
      next_row[column_index] == SPLITTER
    end

    uniq_reachable_splitter_indexes_in_next_row = reachable_splitter_indexes_in_next_row.to_set

    splitters_in_next_row.each do |i|
      unless uniq_reachable_splitter_indexes_in_next_row.include?(i)
        next_row[i] = "."
      end
    end

    uniq_reachable_splitter_indexes_in_next_row.each do |splitter_index|
      path_count = paths_arriving_at_index[splitter_index]
      paths_arriving_at_index[splitter_index] = 0
      paths_arriving_at_index[splitter_index - 1] += path_count
      paths_arriving_at_index[splitter_index + 1] += path_count
    end
  end

  def total_paths = paths_arriving_at_index.sum

  def next_row
    rows[current_row_index + 1]
  end

  def current_row_starting_points
    starting_points_for(current_row_index)
  end

  def current_row_starting_point
    current_row.chars.index { |char| char == STARTING_POINT }
  end

  def splitters_in_next_row
    current_row = rows[current_row_index + 1]
    indices = []

    current_row.chars.each.with_index do |char, i|
      if char == SPLITTER
        indices << i
      end
    end

    indices
  end

  def starting_points_for(row_index)
    indices = []

    paths_arriving_at_index.each.with_index do |path_count, i|
      indices << i unless path_count.zero?
    end
    indices
  end

  def current_row = rows[current_row_index]
end

inputs_string = File.read("inputs.txt")

grid = Grid.new(inputs_string)
puts grid.process_beam
