#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"

require_relative "presents_and_regions"

inputs_file = "inputs_test.txt"
# inputs_file = "inputs.txt"

presents_and_regions = PresentsAndRegions.new(inputs_file)

present = presents_and_regions.presents[1]

puts present
puts
puts present.flip
puts
present = present.rotate
puts present
puts
present = present.rotate
puts present
puts
present = present.rotate
puts present
puts
present = present.rotate
puts present
puts
