#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"

require_relative "presents_and_regions"
require_relative "present_fitter"

inputs_file = "inputs_test.txt"
# inputs_file = "inputs.txt"

presents_and_regions = PresentsAndRegions.new(inputs_file)

present_shapes = presents_and_regions.present_shapes

can_fit = 0

presents_and_regions.region_to_present_counts.each_pair do |region, present_counts|
  fitter = PresentFitter.new(present_shapes:, present_counts:, region:)

  can_fit += 1 if fitter.can_fill?
end

puts can_fit
