AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

inherit_gem:
  foobara-rubocop-rules:
    - rules/*

Naming/FileName:
  inherit_mode:
    merge:
      - Exclude

Naming/MethodParameterName:
  Enabled: false


Style/MinMaxComparison:
  Enabled: false
