#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"
require "fileutils"

inputs_file = "inputs_test.txt"
# inputs_file = "inputs.txt"
wait_on_cache = inputs_file != "inputs.txt"

class NetworkPath
  @existing = {}

  class << self
    def new(value, list = nil)
      key = [value, list]

      @existing[key] ||= super
    end
  end

  attr_accessor :value, :list

  def initialize(value, list = nil)
    self.value = value
    self.list = list
  end

  def each_part(&block)
    block.call(value)

    list&.each_part(&block)
  end

  def hash
    # rubocop:disable Security/CompoundHash
    value.hash + list.hash
    # rubocop:enable Security/CompoundHash
  end

  def ==(other)
    other.class == self.class && other.value == value && other.list == list
  end

  def eql?(other) = self == other
end

class CacheThread < Thread
  class << self
    def load_cache(inputs_file_name)
      cache_file_name = self.cache_file_name(inputs_file_name)
      cache = {}

      if File.exist?(cache_file_name)
        FileUtils.cp cache_file_name, "#{cache_file_name}.bak"

        begin
          File.open(cache_file_name) do |f|
            until f.eof?
              path = read_path(f)
              count = read_result(f)
              cache[path] = count
            end
          end
        rescue EOFError
          warn "cache corrupted, dumping out good values"
          # rubocop:disable Style/FileOpen
          cache_file = File.open(cache_file_name, "w")
          # rubocop:enable Style/FileOpen

          cache.each_pair do |path, count|
            write(cache_file, path, count)
          end

          cache_file.close

          FileUtils.cp cache_file_name, "#{cache_file_name}.bak"
        end
      end

      cache
    end

    def cache_file_name(inputs_file_name)
      "#{inputs_file_name}.cache"
    end

    def write(file, path, result)
      path.each_part do |path_part|
        file.write(Marshal.dump(path_part))
      end

      file.write(Marshal.dump(:path_end))
      file.write(Marshal.dump(result))
    end

    def read_path(file)
      path_array = []

      loop do
        path_part = Marshal.load(file)

        break if path_part == :path_end

        unless path_part.is_a?(Symbol)
          raise "wtf"
        end

        path_array << path_part
      end

      path_array.reverse.inject(nil) do |path, path_part_symbol|
        NetworkPath.new(path_part_symbol, path)
      end
    end

    def read_result(file)
      Marshal.load(file)
    end
  end

  attr_accessor :inputs_file_name, :cache, :queue

  def initialize(inputs_file_name, cache)
    self.inputs_file_name = inputs_file_name
    self.queue = Queue.new

    super { do_it }
  end

  def do_it
    until queue.closed?
      path = queue.pop

      break if path == :stop

      count = queue.pop

      if path && count
        file = cache_file
        puts "caching:"
        puts path.inspect
        puts count.inspect
        self.class.write(file, path, count)
        file.flush
      end
    end
  end

  def dirty! = queue << true
  def stop = queue << :stop

  def close!
    stop
    queue.close
  end

  def write_to_cache(path, count)
    queue << path
    queue << count
  end

  def cache_file
    return @cache_file if @cache_file

    cache_file_name = self.class.cache_file_name(inputs_file_name)

    if File.exist?(cache_file_name)
      FileUtils.mv(cache_file_name, "#{cache_file_name}.bak")
    end

    # rubocop:disable Style/FileOpen
    @cache_file = File.open(cache_file_name, "a")
    # rubocop:enable Style/FileOpen
  end

  def cache_file_name
    @cache_file_name ||= self.class.cache_file_name(inputs_file_name)
  end
end

class Network
  attr_accessor :graph, :start_at, :seen, :cache, :inputs_file, :cache_thread, :wait_on_cache

  def initialize(inputs_file, start_at, wait_on_cache: false)
    self.inputs_file = inputs_file
    self.start_at = start_at
    self.wait_on_cache = wait_on_cache

    inputs = File.read(inputs_file)

    lines = inputs.split("\n")

    self.graph = {}

    lines.each do |line|
      if line =~ /(\w+):(.*)/
        source = $1
        destination = $2.scan(/\w+/)

        graph[source.to_sym] = destination.map(&:to_sym)
      else
        raise "Unexpected line #{line}"
      end
    end
  end

  def answer
    self.seen = Set.new
    self.cache = CacheThread.load_cache(inputs_file)
    self.cache_thread = CacheThread.new(inputs_file, cache)

    path_count_from(start_at, seen_fft: false, seen_dac: false, path: nil)
  ensure
    self.seen = nil

    if wait_on_cache
      cache_thread.stop
    else
      cache_thread.close!
    end
  end

  def join = cache_thread.join

  private

  def cached(path)
    result = cache[path]

    if result
      puts "Cache hit on #{path}: #{result}"
    else
      puts "Cache miss on #{path}"
    end

    unless result
      result = yield

      cache[path] = result

      cache_thread.write_to_cache(path, result)
    end

    result
  end

  def path_count_from(node, seen_fft:, seen_dac:, path:)
    path = NetworkPath.new(node, path)

    return 0 if seen.include?(path)

    seen << path

    cached(path) do
      case node
      when :fft
        seen_fft = true
      when :dac
        seen_dac = true
      end

      destinations = graph[node]

      destinations.map do |destination|
        if destination == :out
          if seen_fft && seen_dac
            puts "found a path!!"
            1
          else
            0
          end
        else
          path_count_from(destination, seen_fft:, seen_dac:, path:)
        end
      end.sum
    end
  end
end

network = Network.new(inputs_file, :svr, wait_on_cache:)
puts network.answer

network.join
