#!/usr/bin/env ruby

require "pry"
# require "pry-byebug"

inputs_file = "inputs_test.txt"
inputs_file = "inputs.txt"

class Network
  attr_accessor :graph, :start_at

  def initialize(inputs_file, start_at)
    self.start_at = start_at

    inputs = File.read(inputs_file)

    lines = inputs.split("\n")

    self.graph = {}

    lines.each do |line|
      if line =~ /(\w+):(.*)/
        source = $1
        destination = $2.scan(/\w+/)

        graph[source.to_sym] = destination.map(&:to_sym)
      else
        raise "Unexpected line #{line}"
      end
    end
  end

  def answer = path_count_from(start_at, seen_fft: false, seen_dac: false)

  private

  def path_count_from(node, seen_fft:, seen_dac:)
    case node
    when :fft
      seen_fft = true
    when :dac
      seen_dac = true
    end

    destinations = graph[node]

    destinations.map do |destination|
      if destination == :out
        seen_fft && seen_dac ? 1 : 0
      else
        path_count_from(destination, seen_fft:, seen_dac:)
      end
    end.sum
  end
end

network = Network.new(inputs_file, :svr)
puts network.answer
