#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"

require_relative "floor"

def parse_points(filename)
  input_string = File.read(filename)
  rows = input_string.split("\n")

  rows.map do |row|
    coordinates = row.split(",").map(&:to_i)
    Point[*coordinates]
  end
end

points = parse_points("inputs.txt")

floor = Floor.new(points)

biggest = floor.biggest_red_tile_defined_rectangle_containing_all_green_or_red_tiles
puts biggest.area

# 1395519733
