#!/usr/bin/env ruby

# require "simplecov"

# SimpleCov.start

require_relative "floor"
require "pry"
# require "pry-byebug"

def r(x1, y1, x2, y2)
  Rectangle.new(Point[x1, y1], Point[x2, y2])
end

def assert_rectangles(actual, expected)
  actual = actual.sort
  expected = expected.sort

  if actual == expected
    print "."
  else
    puts
    warn "Expected: #{expected.map(&:to_s)}"
    warn "     Got: #{actual.map(&:to_s)}"
    exit 1
  end
end

def assert_equal(actual, expected)
  if actual == expected
    print "."
  else
    puts
    warn "Expected: #{expected}"
    warn "     Got: #{actual}"
    exit 1
  end
end

points = [
  Point[2, 1],
  Point[6, 1],
  Point[6, 5],
  Point[5, 5],
  Point[5, 4],
  Point[3, 4],
  Point[3, 5],
  Point[2, 5]
]

ring = Ring.new(points)
assert_rectangles(
  ring.extract_rectangles,
  [
    Rectangle.new(Point[2, 1], Point[6, 4]),
    Rectangle.new(Point[2, 4], Point[3, 5]),
    Rectangle.new(Point[5, 4], Point[6, 5])
  ]
)

floor = Floor.new(points)

biggest = floor.biggest_red_tile_defined_rectangle_containing_all_green_or_red_tiles

assert_equal(biggest.area, 16)

{
  [[1, 1, 2, 2], [2, 2, 3, 3]] => [[2, 3, 2, 3], [3, 2, 3, 2], [3, 3, 3, 3]],
  [[1, 2, 2, 3], [2, 1, 3, 2]] => [[2, 1, 2, 1], [3, 1, 3, 1], [3, 2, 3, 2]],
  [[2, 2, 3, 3], [1, 1, 2, 2]] => [[1, 1, 1, 1], [2, 1, 2, 1], [1, 2, 1, 2]],
  [[2, 1, 3, 2], [1, 2, 2, 3]] => [[1, 2, 1, 2], [1, 3, 1, 3], [2, 3, 2, 3]],
  [[1, 0, 2, 3], [2, 1, 3, 2]] => [[3, 1, 3, 2]],
  [[0, 1, 3, 2], [1, 0, 2, 1]] => [[1, 0, 2, 0]],
  [[1, 0, 2, 3], [0, 1, 1, 2]] => [[0, 1, 0, 2]],
  [[0, 0, 3, 1], [1, 1, 2, 2]] => [[1, 2, 2, 2]],
  [[1, 1, 2, 1], [2, 1, 3, 1]] => [[3, 1, 3, 1]],
  [[0, 1, 0, 2], [0, 0, 0, 1]] => [[0, 0, 0, 0]],
  [[2, 1, 3, 1], [1, 1, 2, 1]] => [[1, 1, 1, 1]],
  [[0, 0, 0, 1], [0, 1, 0, 2]] => [[0, 2, 0, 2]],
  [[1, 1, 4, 1], [3, 1, 6, 1]] => [[5, 1, 6, 1]],
  [[0, 0, 0, 3], [0, 2, 0, 5]] => [[0, 4, 0, 5]],
  [[1, 1, 6, 1], [3, 1, 4, 1]] => [],
  [[0, 0, 2, 2], [2, 0, 2, 0]] => [],
  [[1, 1, 4, 2], [3, 1, 6, 2]] => [[5, 1, 6, 2]],
  [[3, 0, 3, 3], [1, 1, 4, 1]] => [[1, 1, 2, 1], [4, 1, 4, 1]],
  [[1, 1, 4, 1], [3, 0, 3, 3]] => [[3, 0, 3, 0], [3, 2, 3, 3]],
  [[1, 0, 3, 2], [2, 1, 3, 2]] => [],
  [[1, 0, 3, 2], [3, 2, 3, 2]] => [],
  [[3, 2, 4, 3], [1, 1, 6, 4]] => [
    [1, 1, 2, 1], [3, 1, 4, 1], [5, 1, 6, 1],
    [1, 2, 2, 3], [5, 2, 6, 3],
    [1, 4, 2, 4], [3, 4, 4, 4], [5, 4, 6, 4]
  ],
  [[1, 0, 2, 1], [0, 1, 3, 2]] => [[0, 1, 0, 2], [1, 2, 2, 2], [3, 1, 3, 2]],
  [[0, 1, 1, 2], [1, 0, 2, 3]] => [[1, 0, 2, 0], [2, 1, 2, 2], [1, 3, 2, 3]],
  [[1, 1, 2, 2], [0, 0, 3, 1]] => [[0, 0, 0, 1], [1, 0, 2, 0], [3, 0, 3, 1]],
  [[2, 0, 2, 0], [0, 0, 2, 2]] => [[0, 0, 1, 0], [0, 1, 1, 2], [2, 1, 2, 2]],
  [[1, 0, 2, 1], [0, 0, 2, 2]] => [[0, 0, 0, 1], [0, 2, 0, 2], [1, 2, 2, 2]],
  [[1, 0, 2, 0], [0, 0, 2, 2]] => [[0, 0, 0, 0], [0, 1, 0, 2], [1, 1, 2, 2]],
  [[2, 0, 3, 0], [0, 0, 2, 2]] => [[0, 0, 1, 0], [0, 1, 1, 2], [2, 1, 2, 2]],
  [[1, 1, 3, 2], [0, 0, 2, 3]] => [[0, 0, 2, 0], [0, 1, 0, 2], [0, 3, 2, 3]],
  [[0, 0, 0, 1], [0, 0, 2, 2]] => [[1, 0, 2, 1], [0, 2, 0, 2], [1, 2, 2, 2]],
  [[0, 2, 1, 2], [0, 0, 2, 2]] => [[0, 0, 1, 1], [2, 0, 2, 1], [2, 2, 2, 2]],
  [[2, 1, 2, 2], [0, 0, 2, 2]] => [[0, 0, 1, 0], [2, 0, 2, 0], [0, 1, 1, 2]],
  [[0, 0, 0, 1], [0, 1, 2, 3]] => [[1, 1, 2, 1], [0, 2, 0, 3], [1, 2, 2, 3]],
  [[0, 3, 1, 3], [1, 1, 3, 3]] => [[1, 1, 1, 2], [2, 1, 3, 2], [2, 3, 3, 3]],
  [[3, 2, 3, 3], [1, 0, 3, 2]] => [[1, 0, 2, 1], [3, 0, 3, 1], [1, 2, 2, 2]],
  [[0, 0, 3, 0], [2, 0, 5, 2]] => [[4, 0, 5, 0], [2, 1, 3, 2], [4, 1, 5, 2]],
  [[0, 2, 0, 5], [0, 0, 2, 3]] => [[0, 0, 0, 1], [1, 0, 2, 1], [1, 2, 2, 3]],
  [[2, 5, 5, 5], [0, 3, 3, 5]] => [[0, 3, 1, 4], [2, 3, 3, 4], [0, 5, 1, 5]],
  [[5, 0, 5, 3], [3, 2, 5, 5]] => [[3, 2, 4, 3], [3, 4, 4, 5], [5, 4, 5, 5]],
  [[0, 0, 1, 1], [2, 2, 3, 3]] => [[2, 2, 3, 3]],
  [[0, 0, 2, 2], [0, 0, 2, 2]] => [],
  [[0, 0, 0, 0], [0, 0, 0, 0]] => []
}.each_pair do |green_and_red_rectangle, expected_rectangles|
  green_and_red_rectangle => [
    [green_x1, green_y1, green_x2, green_y2],
    [red_x1, red_y1, red_x2, red_y2]
  ]

  green_rectangle = r(green_x1, green_y1, green_x2, green_y2)
  red_rectangle = r(red_x1, red_y1, red_x2, red_y2)

  remaining = green_rectangle.remove_overlapping_pieces(red_rectangle)
  remaining = [*remaining]
  expected_rectangles = expected_rectangles.map { r(*it) }

  assert_rectangles(remaining, expected_rectangles)
end

points = [
  Point[9, 1],
  Point[10, 1],
  Point[10, 2],
  Point[18, 2],
  Point[18, 3],
  Point[15, 3],
  Point[15, 8],
  Point[14, 8],
  Point[14, 3],
  Point[12, 3],
  Point[12, 7],
  Point[11, 7],
  Point[11, 3],
  Point[8, 3],
  Point[8, 2],
  Point[9, 2]
]

floor = Floor.new(points)

biggest = floor.biggest_red_tile_defined_rectangle_containing_all_green_or_red_tiles

assert_equal(biggest.area, 22)
assert_equal(biggest, Rectangle.new(Point[8, 2], Point[18, 3]))

puts
