#!/usr/bin/env ruby

require_relative "rectangle"

def r(x1, y1, x2, y2)
  Rectangle.new(Point[x1, y1], Point[x2, y2])
end

def assert_rectangles(actual, expected)
  if actual.sort == expected.sort
    print "."
  else
    warn "Expected #{actual.map(&:to_s)} to == #{expected.map(&:to_s)}"
  end
end

{
  [[1, 1, 2, 2], [2, 2, 3, 3]] => [[2, 3, 2, 3], [3, 2, 3, 2], [3, 3, 3, 3]],
  [[1, 0, 2, 3], [2, 1, 3, 2]] => [[3, 1, 3, 2]],
  [[1, 1, 2, 1], [2, 1, 3, 1]] => [[3, 1, 3, 1]],
  [[1, 1, 4, 1], [3, 1, 6, 1]] => [[5, 1, 6, 1]],
  [[3, 0, 3, 3], [1, 1, 4, 1]] => [[1, 1, 2, 1], [4, 1, 4, 1]]
}.each_pair do |green_and_red_rectangle, expected_rectangles|
  green_and_red_rectangle => [
    [green_x1, green_y1, green_x2, green_y2],
    [red_x1, red_y1, red_x2, red_y2]
  ]

  green_rectangle = r(green_x1, green_y1, green_x2, green_y2)
  red_rectangle = r(red_x1, red_y1, red_x2, red_y2)

  remaining = green_rectangle.remove_overlapping_pieces(red_rectangle)
  remaining = [*remaining]
  expected_rectangles = expected_rectangles.map { r(*it) }

  assert_rectangles(remaining, expected_rectangles)
end

puts
