#!/usr/bin/env ruby

# require "simplecov"

# SimpleCov.start

require_relative "machine_parser"
require "pry"
# require "pry-byebug"

def assert_equal(actual, expected)
  if actual == expected
    print "."
  else
    puts
    warn "Expected: #{expected}"
    warn "     Got: #{actual}"
    exit 1
  end
end

def assert_is_a(actual, expected_class)
  if actual.is_a?(expected_class)
    print "."
  else
    puts
    warn "Expected instance of: #{expected_class}"
    warn "     Got instance of: #{actual.class}"
    exit 1
  end
end

machines = MachineParser.parse("inputs2.txt")

machines.sort_by!(&:crude_max_pushes)

all = []

machines.each do |machine|
  min_pushes = machine.minimum_pushes_required
  all << min_pushes
  assert_is_a(min_pushes, Integer)
end

puts all.sum
