#!/usr/bin/env ruby

require "pry"
# require "pry-byebug"

require_relative "machine_parser"

# machines = MachineParser.parse("inputs_test.txt")
# currently on 160:
# machines = MachineParser.parse("inputs_min_joltage_chaos.txt")
machines = MachineParser.parse("inputs_smallest_joltage.txt")

Machine.load_cache_from_file

machines.sort_by!(&:crude_max_pushes)

pushes = machines.map do |machine|
  puts "#{Time.now}: starting new machine..."
  push_count = machine.minimum_pushes_required

  if push_count.nil?
    puts "nil push count wtf!!"
    puts machine
    binding.pry
  end
end

sum = pushes.sum

puts "found sum! #{sum}"

Machine.close_cache_file

# First possible answer submitted:   17554 but too low uggg
# Next possible answer we generated (I think min joltage selected): 17953 but too high uggggggg
# 18010
