#!/usr/bin/env ruby

require "yaml"

# require "pry"
# require "pry-byebug"

require_relative "minimum_pushes_cache"
require_relative "machine_parser"

# suffix = "index_of_min_joltage_for_biggest_buttons"
# suffix = "joltage_index_with_fewest_buttons"
# suffix = "joltage_index_of_smallest_joltage"
suffix = "joltage_index_of_biggest_joltage"

MinimumPushesCache.cache_file_name = "#{suffix}.cache"
Caps.caps_file = "caps_#{suffix}.yml"
inputs_file = "inputs.txt"

print_files_in_use = proc do
  puts "running for #{inputs_file} #{MinimumPushesCache.cache_file_name} with #{Caps.caps_file}"
end

print_files_in_use.call

machines = MachineParser.parse(inputs_file)

MinimumPushesCache.load_cache_from_file

machines.sort_by!(&:crude_max_pushes)

pushes = machines.map do |machine|
  puts "#{Time.now}: starting new machine..."
  push_count = machine.minimum_pushes_required

  if push_count.nil?
    puts "nil push count wtf!!"
    puts machine
    binding.pry
  end

  puts "solution for:"
  puts machine.to_s_parsable
  puts push_count
  puts

  print_files_in_use.call

  Caps.update_cap_if_needed(machine, push_count)

  push_count
end

sum = pushes.sum

puts "found sum! #{sum}"

MinimumPushesCache.close_cache_file

# First possible answer submitted:   17554 but too low uggg
# Next possible answer we generated (I think min joltage selected): 17953 but too high uggggggg
# 18010
