#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"

require_relative "machine_parser"

machines = MachineParser.parse("inputs_test.txt")

Machine.load_cache_from_file

machines.sort_by!(&:crude_max_pushes)

sum = machines.map do |machine|
  puts "#{Time.now}: starting new machine..."
  machine.minimum_pushes_required
end.sum

puts "found sum! #{sum}"

Machine.close_cache_file
