#!/usr/bin/env ruby

class Dial
  attr_accessor :position

  def initialize = self.position = 50

  def turn_left(i)
    self.position -= i
    normalize
  end

  def turn_right(i)
    self.position += i
    normalize
  end

  def zero? = position.zero?

  private

  def normalize = self.position %= 100
end

class DeterminePassword
  class << self
    def process_inputs(...)= new(...)
  end

  attr_accessor :dial, :zeroes_counter

  def initialize
    self.dial = Dial.new
    self.zeroes_counter = 0
  end

  def process_inputs(inputs)
    inputs.each do |input|
      process_input(input)
    end

    zeroes_counter
  end

  private

  def process_input(input)
    if input.left?
      turn_left(input.clicks)
    else
      turn_right(input.clicks)
    end

    self.zeroes_counter += 1 if zero?
  end

  def turn_left(...) = dial.turn_left(...)
  def turn_right(...) = dial.turn_right(...)
  def zero? = dial.zero?
end

class Input
  attr_accessor :left, :clicks

  def initialize(left, clicks)
    self.left = left
    self.clicks = clicks
  end

  def left? = left

  def to_s = "#{left? ? "L" : "R"}#{clicks}"
end

class InputsParser
  class << self
    def parse(filename)
      File.readlines(filename).map do |line|
        match = /\A(R|L)(\d+)\z/.match(line.chomp)

        Input.new(match[1] == "L", match[2].to_i)
      end
    end
  end
end

inputs = InputsParser.parse("inputs.txt")

password = DeterminePassword.new.process_inputs(inputs)

puts password
