#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"

require_relative "presents_and_regions"

inputs_file = "inputs_test.txt"
# inputs_file = "inputs.txt"

presents_and_regions = PresentsAndRegions.new(inputs_file)

puts presents_and_regions
